---
title: "Assignment 5"
---

# Base R Plots

## Histogram

```{r, warning=FALSE, message=FALSE, results='hide'}
library(tidyverse)

# Cleaning Data
setwd("E:/Fall 2024 (Semester 7)/EPPS 6356/Assignment 4")
data <- read.csv("DV_ProjectData.csv")
data.tx <- data %>%
  filter(State == "TX" & CountyName != "Texas")
data.selectedstates <- data %>%
  filter(CountyName == "Texas" | CountyName == "New York" | CountyName == "California" |
           CountyName == "Florida" | CountyName == "Wisconsin" | CountyName == "Montana")

# Histogram
par(bg="gray70", fg="black", family="serif", cex=0.9, mar=c(4,4,3.5,2))

hist(data.tx$FoodEnviornmentIndex, breaks=9, col="forestgreen", border="gold1",
     main="Food Enviornment Index Scores Frequency for Texas Counties", cex.main=1.5,
     axes=FALSE, xlab=" ", ylab=" ")
axis(1, at=0:8)
axis(2, at=c(0, 15, 30, 45, 60, 75, 90))
box(bty="l")
abline(h=90, col="white", lty="longdash", lwd=2)
abline(h=33, col="gray90", lty="dashed", lwd=2)
text(x=2, y=33, labels="y = 33", pos=3, col="gray20", cex=1.1)
mtext("FEI Score", side=1, line=2.5, cex=1.2)
mtext("# of Counties", side=2, line=2.5, cex=1.2)
```

## Bar Chart

### Vertical Bars

```{r, warning=FALSE, message=FALSE, results='hide'}
par(bg="gray70", fg="black", family="serif", cex=0.9)
barcolors <- ifelse(data.selectedstates$CountyName == "Texas", "forestgreen", "springgreen3")
barborders <- ifelse(data.selectedstates$CountyName == "Texas", "gold1", "darkgreen")

barplot(data.selectedstates$FoodEnviornmentIndex, space=0.15, axes=FALSE, col=barcolors, 
        border=barborders, main="Average Food Environment Index Score for Selected States",
        cex.main=1.5, names.arg=data.selectedstates$CountyName, cex.names=1.1)
axis(2, at=c(0, 2, 4, 6, 8, 9))
abline(h=6, col="white", lty="longdash", lwd=2)
box(bty="u")
```

### Horizonal

```{r, warning=FALSE, message=FALSE, results='hide'}
par(mar=c(2.5,3,6,2))
par(bg="gray70", fg="black", family="serif", cex=0.9)
barplot(data.selectedstates$FoodEnviornmentIndex, space=0.25, axes=FALSE, col=barcolors, 
        border=barborders, names.arg=data.selectedstates$State, horiz=TRUE)
axis(1, at=c(0, 2, 4, 6, 8, 9))
axis(3, at=c(0, 2, 4, 6, 8, 9))
mtext("Average Food Environment Index Score for Selected States", side=3, line=4.5, cex=1.5,
      font=2)
mtext("FEI Score", side=3, line=2.25, cex=1.1)
box(bty="]")
```

## Pie Chart

```{r, warning=FALSE, message=FALSE, results='hide'}
piedataCA <- c(data.selectedstates$VoterTurnoutRate[1], 1 - data.selectedstates$VoterTurnoutRate[1])
piedataFL <- c(data.selectedstates$VoterTurnoutRate[2], 1 - data.selectedstates$VoterTurnoutRate[2])
piedataTX <- c(data.selectedstates$VoterTurnoutRate[5], 1 - data.selectedstates$VoterTurnoutRate[5])
piedataNY <- c(data.selectedstates$VoterTurnoutRate[4], 1 - data.selectedstates$VoterTurnoutRate[4])

par(bg="gray70", fg="black", family="serif", cex=0.9)
par(mfrow=c(2, 2), mar=c(1, 1, 1, 1))
pie(piedataCA, col = c("firebrick1", "mediumblue"), labels = NA, clockwise = TRUE,
    main="Califnornia Voter Turnout", cex.main=1.3)
pie(piedataNY, col = c("firebrick1", "mediumblue"), labels = NA, clockwise = TRUE,
    main="New York Voter Turnout", cex.main=1.3)
pie(piedataTX, col = c("firebrick1", "mediumblue"), labels = NA, clockwise = TRUE,
    main="Texas Voter Turnout", cex.main=1.3)
pie(piedataFL, col = c("firebrick1", "mediumblue"), labels = NA, clockwise = TRUE,
    main="Florida Voter Turnout", cex.main=1.3)

par(mfrow=c(1, 1))
legend("center", legend=c("Turnout", "Non-Turnout"), 
       fill=c("firebrick1", "mediumblue"))
```

## Box Plot

```{r, warning=FALSE, message=FALSE, results='hide'}
library(readxl)
setwd("E:/Fall 2024 (Semester 7)/EPPS 6356/Assignment 5")
Key <- read_excel("County Regions Key.xlsx") #County Regions defined with help from Copilot AI
data.tx <- data.tx %>%
  mutate(Region = with(Key, region[match(CountyName, county)]))

par(bg="gray70", fg="black", family="serif", cex=0.9)
par(mar=c(2.5, 4, 3.5, 1))
boxplot(data.tx$VoterTurnoutRate ~ data.tx$Region, data.tx,
        boxwex = 0.7, col="turquoise1", main="Voter Turnout in Texas Counties by Region", 
        names = c("Central TX", "East TX", "North TX", "South TX", "Panhandle", 
                  "Upper Gulf", "West TX"), cex.main=1.5, xlab="", ylab="Voter Turnout Rate", 
        pch=23, bg="turquoise1", border="navy")
```

## Scatter Plot

```{r, warning=FALSE, message=FALSE, results='hide'}
par(bg="gray70", fg="black", family="serif", cex=0.9)
par(mar=c(4,4,3.5,1))
plot(data.tx$MedianHouseholdIncome, data.tx$VoterTurnoutRate, 
     pch=23, bg="turquoise1", col="navy", xlab="Median Household Income", ylab="Voter Turnout Rate",
     main="Household Income vs Voter Turnout by Texas County", cex.main=1.5)
```

# ggplot Plots

## Histogram

```{r, warning=FALSE, message=FALSE, results='hide'}
ggplot(data.tx, aes(x=FoodEnviornmentIndex)) + 
  geom_histogram(binwidth=1, fill="forestgreen", color="gold1") +
  labs(x="Food Enviornment Index", y="# of Counties", 
       title="Food Enviornment Index Scores Frequency for Texas Counties") + 
  theme_classic(base_family = "serif") + 
  theme(plot.background = element_rect(fill = "gray70"), 
        panel.background = element_rect(fill = "gray70"),
        plot.title = element_text(face = "bold", hjust = 0.5, size = 15)) + 
  scale_x_continuous(breaks=seq(0, 9, by=1)) + scale_y_continuous(breaks=seq(0, 90, by=15))
```

## Bar Chart

### Vertical Bars

```{r, warning=FALSE, message=FALSE, results='hide'}
ggplot(data.selectedstates, aes(x=CountyName, y=FoodEnviornmentIndex)) +
  geom_bar(stat="identity", fill=barcolors, color=barborders) +
  labs(x="", y="FEI Score", title="Average Food Environment Index Score for Selected States") +
  theme_classic(base_family = "serif") + 
  theme(panel.background = element_rect(fill = "gray70"),
        plot.background = element_rect(fill = "gray70"),
        plot.title = element_text(face = "bold", hjust = 0.5, size = 16)) + 
  scale_y_continuous(breaks=seq(0, 9, by=1))
```

### Horizontal

```{r, warning=FALSE, message=FALSE, results='hide'}
ggplot(data.selectedstates, aes(x=CountyName, y=FoodEnviornmentIndex)) +
  geom_bar(stat="identity", fill=barcolors, color=barborders) +
  labs(x="", y="FEI Score", title="Average Food Environment Index Score for Selected States") +
  theme_classic(base_family = "serif") + 
  theme(panel.background = element_rect(fill = "gray70"),
        plot.background = element_rect(fill = "gray70"),
        plot.title = element_text(face = "bold", hjust = 0.5, size = 15)) + 
  scale_y_continuous(breaks=seq(0, 9, by=1)) + 
  coord_flip()
```

## Pie Chart

```{r, warning=FALSE, message=FALSE, results='hide'}
ggplot(, aes(x="", y=piedataTX, fill = c("Turnout", "Non-Turnout"))) +
  geom_bar(stat="identity") + coord_polar(theta="y") + 
  labs(title="Texas Voter Turnout", fill = "Turnout") +
  scale_fill_manual(values=c("Turnout"="firebrick1", "Non-Turnout"="mediumblue")) +
  theme_void(base_family = "serif") +
  theme(plot.title = element_text(size=18, hjust=0.5, face="bold"), 
        plot.background = element_rect(fill = "gray70"))
```

## Box Plot

```{r, warning=FALSE, message=FALSE, results='hide'}
ggplot(data.tx, aes(Region, VoterTurnoutRate)) +
  geom_boxplot(fill = "turquoise1", outlier.color = "navy", outlier.fill = "turquoise1",
               outlier.shape=23, outlier.size=2.25, staplewidth=0.5) + 
  labs(title="Voter Turnout of Texas Counties by Region") + xlab("") + ylab("Voter Turnout Rate") + 
  theme_classic(base_family = "serif") +
  theme(panel.background = element_rect(fill = "gray70"),
        plot.background = element_rect(fill = "gray70"),
        plot.title = element_text(face = "bold", hjust = 0.5, size = 18),
        axis.text.x = element_text(angle=25, hjust=1, size=11),
        axis.text.y = element_text(size=11)) + 
  scale_y_continuous(breaks=seq(0.4, 1.0, by=0.1))
```

## Scatter Plot

```{r, warning=FALSE, message=FALSE, results='hide'}
ggplot(data.tx, aes(MedianHouseholdIncome, VoterTurnoutRate)) + 
  geom_point(shape = 23, color = "navy", fill = "turquoise1", size = 2.25) + 
  theme_classic(base_family = "serif") + 
  labs(title="Household Income vs Voter Turnout by Texas County") + 
  theme(plot.background = element_rect(fill = "gray70"), 
        panel.background = element_rect(fill = "gray70"),
        plot.title = element_text(face = "bold", hjust = 0.5, size = 18)) + 
  scale_x_continuous(breaks=seq(35000, 125000, by=15000)) + 
  scale_y_continuous(breaks=seq(0.4, 1.0, by=0.1))
```

# Exporting charts using different formats

```{r, warning=FALSE, message=FALSE, results='hide'}
## PDF
pdf("assignment5.pdf")

par(bg="gray70", fg="black", family="serif", cex=0.9, mar=c(4,4,3.5,2))
hist(data.tx$FoodEnviornmentIndex, breaks=9, col="forestgreen", border="gold1",
     main="Food Enviornment Index Scores Frequency for Texas Counties", cex.main=1.5,
     axes=FALSE, xlab=" ", ylab=" ")
axis(1, at=0:8)
axis(2, at=c(0, 15, 30, 45, 60, 75, 90))
box(bty="l")
abline(h=90, col="white", lty="longdash", lwd=2)
abline(h=33, col="gray90", lty="dashed", lwd=2)
text(x=2, y=33, labels="y = 33", pos=3, col="gray20", cex=1.1)
mtext("FEI Score", side=1, line=2.5, cex=1.2)
mtext("# of Counties", side=2, line=2.5, cex=1.2)

dev.off()

## JPEG
jpeg("assignment5.jpg")

par(bg="gray70", fg="black", family="serif", cex=0.9, mar=c(4,4,3.5,2))
hist(data.tx$FoodEnviornmentIndex, breaks=9, col="forestgreen", border="gold1",
     main="Food Enviornment Index Scores Frequency for Texas Counties", cex.main=1.5,
     axes=FALSE, xlab=" ", ylab=" ")
axis(1, at=0:8)
axis(2, at=c(0, 15, 30, 45, 60, 75, 90))
box(bty="l")
abline(h=90, col="white", lty="longdash", lwd=2)
abline(h=33, col="gray90", lty="dashed", lwd=2)
text(x=2, y=33, labels="y = 33", pos=3, col="gray20", cex=1.1)
mtext("FEI Score", side=1, line=2.5, cex=1.2)
mtext("# of Counties", side=2, line=2.5, cex=1.2)

dev.off()

## SVG
svg("assignment5.svg")

par(bg="gray70", fg="black", family="serif", cex=0.9, mar=c(4,4,3.5,2))
hist(data.tx$FoodEnviornmentIndex, breaks=9, col="forestgreen", border="gold1",
     main="Food Enviornment Index Scores Frequency for Texas Counties", cex.main=1.5,
     axes=FALSE, xlab=" ", ylab=" ")
axis(1, at=0:8)
axis(2, at=c(0, 15, 30, 45, 60, 75, 90))
box(bty="l")
abline(h=90, col="white", lty="longdash", lwd=2)
abline(h=33, col="gray90", lty="dashed", lwd=2)
text(x=2, y=33, labels="y = 33", pos=3, col="gray20", cex=1.1)
mtext("FEI Score", side=1, line=2.5, cex=1.2)
mtext("# of Counties", side=2, line=2.5, cex=1.2)

dev.off()

## TIFF
tiff("assignment5.tiff")

par(bg="gray70", fg="black", family="serif", cex=0.9, mar=c(4,4,3.5,2))
hist(data.tx$FoodEnviornmentIndex, breaks=9, col="forestgreen", border="gold1",
     main="Food Enviornment Index Scores Frequency for Texas Counties", cex.main=1.5,
     axes=FALSE, xlab=" ", ylab=" ")
axis(1, at=0:8)
axis(2, at=c(0, 15, 30, 45, 60, 75, 90))
box(bty="l")
abline(h=90, col="white", lty="longdash", lwd=2)
abline(h=33, col="gray90", lty="dashed", lwd=2)
text(x=2, y=33, labels="y = 33", pos=3, col="gray20", cex=1.1)
mtext("FEI Score", side=1, line=2.5, cex=1.2)
mtext("# of Counties", side=2, line=2.5, cex=1.2)

dev.off()

## BMP
bmp("assignment5.bmp")

par(bg="gray70", fg="black", family="serif", cex=0.9, mar=c(4,4,3.5,2))
hist(data.tx$FoodEnviornmentIndex, breaks=9, col="forestgreen", border="gold1",
     main="Food Enviornment Index Scores Frequency for Texas Counties", cex.main=1.5,
     axes=FALSE, xlab=" ", ylab=" ")
axis(1, at=0:8)
axis(2, at=c(0, 15, 30, 45, 60, 75, 90))
box(bty="l")
abline(h=90, col="white", lty="longdash", lwd=2)
abline(h=33, col="gray90", lty="dashed", lwd=2)
text(x=2, y=33, labels="y = 33", pos=3, col="gray20", cex=1.1)
mtext("FEI Score", side=1, line=2.5, cex=1.2)
mtext("# of Counties", side=2, line=2.5, cex=1.2)

dev.off()
```
